### ISSUE TITLE
Unable to mark forum topic as read

### ISSUE THREAD

**Issue by cpwc** [Coursemology/coursemology.org#357]
https://edutech.comp.nus.edu.sg/courses/5/forums/course-and-adminstrative-information

```
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
action: access_denied
controller: static_pages
```

Redirected to: https://edutech.comp.nus.edu.sg/access_denied
```
Sorry dude! You are not authorized to access this page.
```

**Comment by jsyeo** [comment]
Hi @calvinpohwc, thanks for the bug report. Unfortunately, I don't quite understand what's the issue here. Do you mind giving us steps to reproduce the bug?

Also, I understand that http://edutech.comp.nus.edu.sg is hosting a forked version of coursemology and the bug might be from either our side or from github.com/nusedutech/coursemology.org. You might want to alert the devs there too.

Thanks!
