### ISSUE TITLE
Possible to add Python 2.7 support?

### ISSUE THREAD

**Issue by ssyberg** [Coursemology/coursemology.org#446]
I teach a course that uses a lot of scientific libs that require 2.7 still so I'm teaching my course using that version.  Not sure how difficult this would be, but if it's trivial, it'd be a great help to my students.

**Comment by allenwq** [comment]
I think it's possible, I can give it a try this weekend.

**Comment by allenwq** [comment]
@ssyberg I've added Python2.7 on coursemology.

However, I'm not totally sure whether it will work for your scientific libraries or not, because our code evaluator and sandbox assumes that we're using python3 ( I did some refactoring, but that might not be enough, and due to the time limit I'm not able to rewrite the whole thing ).

Also if you want to use external libraries, you should let me know because they must be whitelisted.
